import { prisma } from './prisma';

export const initializeDatabase = async (): Promise<void> => {
  try {
    console.log('Connecting to database via Prisma Client...');
    await prisma.$connect();
    console.log('Prisma Client connected successfully.');

    const count = await prisma.talent.count();
    if (count === 0) {
      console.log('Database empty. Auto-seeding 100% authentic Habesha icons...');
      await seedDatabase();
    } else {
      console.log(`Database verified via Prisma. Total active stars: ${count}`);
    }
  } catch (error) {
    console.error('Database initialization failed with Prisma:', error);
    throw error;
  }
};

export async function seedDatabase(): Promise<void> {
  // 1. Categories
  const categories = [
    { id: 1, name: 'Music & Vocalists', slug: 'music', icon: 'Music', description: 'Legendary Ethiopian singers, songwriters, and contemporary afro-pop pioneers' },
    { id: 2, name: 'Actors & Cinema', slug: 'acting', icon: 'Film', description: 'Award-winning cinema stars, television leads, and drama actors' },
    { id: 3, name: 'Comedy & Humor', slug: 'comedy', icon: 'Smile', description: 'Stand-up masters, sketch comedy stars, and witty roasters' },
    { id: 4, name: 'Athletes & Runners', slug: 'sports', icon: 'Trophy', description: 'Olympic champions, world record marathoners, and athletics pioneers' },
    { id: 5, name: 'Creators & Diaspora', slug: 'creators', icon: 'Sparkles', description: 'Digital creators, YouTubers, podcasters, and diaspora influencers' },
    { id: 6, name: 'Heritage & Culture', slug: 'culture', icon: 'Crown', description: 'Traditional masters, jazz virtuosos, and national cultural icons' },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    });
  }

  // 2. Occasions
  const occasions = [
    { id: 'birthday', name: 'Birthday 🎂', icon: 'Cake' },
    { id: 'new_year', name: 'Ethiopian New Year 🌼', icon: 'Sun' },
    { id: 'wedding', name: 'Wedding / Melse 💍', icon: 'Heart' },
    { id: 'pep_talk', name: 'Pep Talk / Advice ⚡', icon: 'Zap' },
    { id: 'roast', name: 'Roast / Humor 😂', icon: 'Flame' },
    { id: 'anniversary', name: 'Anniversary 🥂', icon: 'Wine' },
    { id: 'graduation', name: 'Graduation 🎓', icon: 'GraduationCap' },
  ];

  for (const occ of occasions) {
    await prisma.occasion.upsert({
      where: { id: occ.id },
      update: occ,
      create: occ,
    });
  }

  // 3. 100% Authentic Habesha Talents
  const talents = [
    {
      id: 'talent_teddy_afro',
      name: 'Teddy Afro',
      handle: 'teddyafro',
      title: 'Legendary Singer & National Icon',
      category_id: 1,
      bio: 'Beloved Ethiopian singer-songwriter whose music touches millions across generations. Book a heartfelt birthday song, blessing, or inspirational message.',
      avatar_url: '/stars/teddy_afro.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 5.0,
      review_count: 142,
      response_time: '⚡ Within 24 hours',
      price_video: 250,
      price_live_call: 450,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: true,
      languages: ['Amharic', 'English'],
      tags: ['Music', 'Icon', 'Legend', 'Amharic', 'Unity'],
    },
    {
      id: 'talent_aster_aweke',
      name: 'Aster Aweke',
      handle: 'asteraweke',
      title: 'Queen of Ethiopian Soul',
      category_id: 1,
      bio: 'Acclaimed international vocalist with timeless soulful hits. Bring warmth, love, and legendary blessings to your special family milestone.',
      avatar_url: '/stars/aster_aweke.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.95,
      review_count: 98,
      response_time: '⚡ Within 24 hours',
      price_video: 200,
      price_live_call: 380,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['Soul', 'Vocalist', 'Queen', 'Classic'],
    },
    {
      id: 'talent_rophnan',
      name: 'Rophnan',
      handle: 'rophnan',
      title: 'Afro-Electronic Pioneer & Visionary DJ',
      category_id: 1,
      bio: 'Electronic music producer blending ancient Ethiopian rhythms with futuristic soundscapes. Request hype shoutouts, graduation pep talks, or unique greetings.',
      avatar_url: '/stars/rophnan.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
      rating: 4.98,
      review_count: 87,
      response_time: '⚡ Within 12 hours',
      price_video: 180,
      price_live_call: 320,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: true,
      languages: ['Amharic', 'English'],
      tags: ['Electronic', 'AfroEDM', 'DJ', 'Youth'],
    },
    {
      id: 'talent_haile_gebrselassie',
      name: 'Haile Gebrselassie',
      handle: 'hailegebrselassie',
      title: '2x Olympic Champion & Marathon Legend',
      category_id: 4,
      bio: 'Two-time Olympic 10,000m gold medalist, businessman, and marathon icon. Book Haile for unforgettable high-energy motivation, business pep talks, and celebrations.',
      avatar_url: '/stars/haile_gebrselassie.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 5.0,
      review_count: 114,
      response_time: '⚡ Within 24 hours',
      price_video: 220,
      price_live_call: 400,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: true,
      languages: ['Amharic', 'English'],
      tags: ['Olympics', 'Running', 'Motivation', 'Business'],
    },
    {
      id: 'talent_kenenisa_bekele',
      name: 'Kenenisa Bekele',
      handle: 'kenenisabekele',
      title: '3x Olympic Champion & Distance Running Legend',
      category_id: 4,
      bio: '3-time Olympic Champion and world record holder. Inspiring runners, corporate leaders, and fans worldwide with winning pep talks.',
      avatar_url: '/stars/kenenisa_bekele.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.96,
      review_count: 73,
      response_time: '⚡ Within 24 hours',
      price_video: 180,
      price_live_call: 320,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: false,
      languages: ['Amharic', 'English', 'Oromiffa'],
      tags: ['Olympics', 'Marathon', 'Athlete', 'GoldMedal'],
    },
    {
      id: 'talent_derartu_tulu',
      name: 'Derartu Tulu',
      handle: 'derartutulu',
      title: 'Olympic Gold Medalist & Athletics Pioneer',
      category_id: 4,
      bio: 'First black African woman to win an Olympic gold medal. President of the Ethiopian Athletics Federation and national hero.',
      avatar_url: '/stars/derartu_tulu.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.97,
      review_count: 62,
      response_time: '⚡ Within 24 hours',
      price_video: 140,
      price_live_call: 260,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: true,
      languages: ['Amharic', 'Oromiffa', 'English'],
      tags: ['Trailblazer', 'OlympicGold', 'Legend', 'Pioneer'],
    },
    {
      id: 'talent_tirunesh_dibaba',
      name: 'Tirunesh Dibaba',
      handle: 'tiruneshdibaba',
      title: '3x Olympic Champion & World Record Legend',
      category_id: 4,
      bio: 'Known as the "Baby-Faced Destroyer", 3-time Olympic gold champion and multi-world champion. Sending personalized motivation & blessings.',
      avatar_url: '/stars/tirunesh_dibaba.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
      rating: 4.98,
      review_count: 54,
      response_time: '⚡ Within 24 hours',
      price_video: 150,
      price_live_call: 280,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: true,
      languages: ['Amharic', 'Oromiffa', 'English'],
      tags: ['Olympics', 'Champion', 'Gold', 'Running'],
    },
    {
      id: 'talent_meseret_defar',
      name: 'Meseret Defar',
      handle: 'meseretdefar',
      title: '2x Olympic 5000m Gold Champion',
      category_id: 4,
      bio: '2-time Olympic Gold Champion and world record breaker. Sharing stories of resilience, faith, and athletic excellence.',
      avatar_url: '/stars/meseret_defar.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.95,
      review_count: 48,
      response_time: '⚡ Within 24 hours',
      price_video: 130,
      price_live_call: 240,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['OlympicGold', 'DistanceRunning', 'Inspiration'],
    },
    {
      id: 'talent_mahmoud_ahmed',
      name: 'Mahmoud Ahmed',
      handle: 'mahmoud_ahmed',
      title: 'Legendary Ethio-Jazz & Soul Pioneer',
      category_id: 1,
      bio: 'Golden era legend and BBC World Music Award winner. Celebrating timeless Ethiopian soul with personal greetings and blessings.',
      avatar_url: '/stars/mahmoud_ahmed.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 5.0,
      review_count: 89,
      response_time: '⚡ Within 24 hours',
      price_video: 150,
      price_live_call: 280,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['EthioJazz', 'Soul', 'GoldenEra', 'Legend'],
    },
    {
      id: 'talent_mulatu_astatke',
      name: 'Mulatu Astatke',
      handle: 'mulatuastatke',
      title: 'Father of Ethio-Jazz & International Maestro',
      category_id: 6,
      bio: 'The father of Ethio-Jazz and global musical pioneer. Sharing musical heritage, inspiring artists, and blessing milestone celebrations.',
      avatar_url: '/stars/mulatu_astatke.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
      rating: 5.0,
      review_count: 67,
      response_time: '⚡ Within 24 hours',
      price_video: 160,
      price_live_call: 300,
      etb_rate: 120,
      verified: true,
      featured: true,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['FatherOfEthioJazz', 'Maestro', 'Vibraphone', 'Heritage'],
    },
    {
      id: 'talent_selam_tesfaye',
      name: 'Selam Tesfaye',
      handle: 'selamtesfaye',
      title: 'Top Ethiopian Film Star & Cinema Lead',
      category_id: 2,
      bio: 'Leading Ethiopian film and drama actress. Bringing drama, warmth, wedding congratulations, and birthday joy to fans worldwide.',
      avatar_url: '/stars/selam_tesfaye.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
      rating: 4.93,
      review_count: 76,
      response_time: '⚡ Within 24 hours',
      price_video: 120,
      price_live_call: 220,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: true,
      languages: ['Amharic', 'English'],
      tags: ['Film', 'Cinema', 'Actress', 'Drama'],
    },
    {
      id: 'talent_danayit_mekbib',
      name: 'Danayit Mekbib',
      handle: 'danayitmekbib',
      title: 'Actress & TV Host Extraordinaire',
      category_id: 2,
      bio: 'Beloved television personality, lifestyle host, and cinema star. Energize your birthday party or surprise a best friend with an upbeat video.',
      avatar_url: '/stars/danayit_mekbib.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
      rating: 4.95,
      review_count: 65,
      response_time: '⚡ Within 24 hours',
      price_video: 110,
      price_live_call: 200,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['TVHost', 'Cinema', 'Lifestyle', 'Media'],
    },
    {
      id: 'talent_meklit_hadero',
      name: 'Meklit Hadero',
      handle: 'meklithadero',
      title: 'Ethio-Jazz Vocalist & TED Senior Fellow',
      category_id: 1,
      bio: 'Acclaimed Ethiopian-American singer and cultural innovator. Bringing jazz, folk, and East African melodies to custom video shoutouts.',
      avatar_url: '/stars/meklit_hadero.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.92,
      review_count: 39,
      response_time: '⚡ Within 24 hours',
      price_video: 110,
      price_live_call: 210,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: false,
      languages: ['Amharic', 'English'],
      tags: ['EthioJazz', 'Diaspora', 'Vocalist', 'TEDFellow'],
    },
    {
      id: 'talent_bofem',
      name: 'Bofem',
      handle: 'bofem',
      title: 'TikTok Comedy Creator',
      category_id: 3,
      bio: 'Viral Ethiopian TikTok comedian bringing genuine laughs, playful roasts, and hilarious birthday wishes.',
      avatar_url: '/stars/bofem.jpg',
      hero_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      rating: 4.91,
      review_count: 82,
      response_time: '⚡ Within 6 hours',
      price_video: 75,
      price_live_call: 140,
      etb_rate: 120,
      verified: true,
      featured: false,
      trending: true,
      languages: ['Amharic', 'English'],
      tags: ['Comedy', 'TikTok', 'Roast', 'Viral'],
    },
  ];

  for (const t of talents) {
    await prisma.talent.upsert({
      where: { id: t.id },
      update: t,
      create: t,
    });
  }

  console.log(`Seeded ${talents.length} 100% authentic Habesha icons successfully!`);
}
